[package]
name = "tiger_rust"
version = "0.1.0"
authors = ["Nathan Lilienthal <nathan@nixpulvis.com>"]
build = "build.rs"

[dependencies.lalrpop-util]
version = "0.9.0"

[build-dependencies.lalrpop]
version = "0.9.0"
