[package]
name = "tiger-syntax"
version = "0.1.0"
authors = ["Nathan Lilienthal <nathan@nixpulvis.com>"]
build = "build.rs"

[dependencies]
lalrpop-util = "*"
unicode-xid = "0.0.2"

[build-dependencies]
lalrpop = "*"
